name: "Full Sweep Scheduler - 1k8k"

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    get-dsr1-configs:
        runs-on: ubuntu-latest
        outputs:
            search-space-config: ${{ steps.get-dsr1-configs.outputs.search-space-config }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - id: get-dsr1-configs
              run: |
                  pip install pydantic
                  CONFIG_JSON=$(python3 ${GITHUB_WORKSPACE}/utils/matrix-logic/generate_sweep_configs.py full-sweep --config-files ${GITHUB_WORKSPACE}/.github/configs/nvidia-master.yaml ${GITHUB_WORKSPACE}/.github/configs/amd-master.yaml --seq-lens 1k8k --model-prefix dsr1)
                  echo "search-space-config=$CONFIG_JSON" >> $GITHUB_OUTPUT

    get-gptoss-configs:
        runs-on: ubuntu-latest
        outputs:
            search-space-config: ${{ steps.get-gptoss-configs.outputs.search-space-config }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - id: get-gptoss-configs
              run: |
                  pip install pydantic
                  CONFIG_JSON=$(python3 ${GITHUB_WORKSPACE}/utils/matrix-logic/generate_sweep_configs.py full-sweep --config-files ${GITHUB_WORKSPACE}/.github/configs/nvidia-master.yaml ${GITHUB_WORKSPACE}/.github/configs/amd-master.yaml --seq-lens 1k8k --model-prefix gptoss)
                  echo "search-space-config=$CONFIG_JSON" >> $GITHUB_OUTPUT

    benchmark-dsr1:
        needs: get-dsr1-configs
        uses: ./.github/workflows/benchmark-tmpl.yml
        name: dsr1 1k8k /
        strategy:
            fail-fast: false
            matrix:
                config: ${{ fromJson(needs.get-dsr1-configs.outputs.search-space-config) }}
        secrets: inherit
        with:
            exp-name: "dsr1_1k8k"
            isl: 1024
            osl: 8192
            max-model-len: 9216
            runner: ${{ matrix.config.runner }}
            image: ${{ matrix.config.image }}
            model: ${{ matrix.config.model }}
            framework: ${{ matrix.config.framework }}
            precision: ${{ matrix.config.precision }}
            tp: ${{ matrix.config.tp }}
            ep: ${{ matrix.config.ep }}
            dp-attn: ${{ matrix.config.dp-attn }}
            conc: ${{ matrix.config.conc }}

    benchmark-gptoss:
        needs: get-gptoss-configs
        uses: ./.github/workflows/benchmark-tmpl.yml
        name: gptoss 1k8k /
        strategy:
            fail-fast: false
            matrix:
                config: ${{ fromJson(needs.get-gptoss-configs.outputs.search-space-config) }}
        secrets: inherit
        with:
            exp-name: "gptoss_1k8k"
            isl: 1024
            osl: 8192
            max-model-len: 9216
            runner: ${{ matrix.config.runner }}
            image: ${{ matrix.config.image }}
            model: ${{ matrix.config.model }}
            framework: ${{ matrix.config.framework }}
            precision: ${{ matrix.config.precision }}
            tp: ${{ matrix.config.tp }}
            ep: ${{ matrix.config.ep }}
            dp-attn: ${{ matrix.config.dp-attn }}
            conc: ${{ matrix.config.conc }}

    collect-dsr1-results:
        needs: benchmark-dsr1
        if: ${{ always() }}
        uses: ./.github/workflows/collect-results.yml
        secrets: inherit
        with:
            exp-name: "dsr1_1k8k"

    collect-gptoss-results:
        needs: benchmark-gptoss
        if: ${{ always() }}
        uses: ./.github/workflows/collect-results.yml
        secrets: inherit
        with:
            exp-name: "gptoss_1k8k"

    calc-success-rate:
        needs: [benchmark-dsr1, benchmark-gptoss]
        if: ${{ always() }}
        runs-on: ubuntu-latest

        env:
            RESULTS_DIR: "results/"
            STATS_FILENAME: "run_stats"
            GITHUB_TOKEN: ${{ secrets.REPO_PAT }}

        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.REPO_PAT }}
                  fetch-depth: 0

            - name: Download results artifacts
              uses: actions/download-artifact@v6
              with:
                  path: ${{ env.RESULTS_DIR }}
                  pattern: results_*

            - name: Install python dependencies
              run: pip install PyGithub

            - name: Calculate success rate
              run: python3 utils/calc_success_rate.py $STATS_FILENAME

            - uses: actions/upload-artifact@v5
              with:
                  name: "run-stats"
                  path: ${{ env.STATS_FILENAME }}.json
